apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        env:
        - name: discovery.type
          value: single-node
        - name: JVM_OPTS
          value: "-Xms1g -Xmx1.5g"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "1.5Gi"
          
---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200