apiVersion: v1
kind: Pod
metadata:
  name: log-app
  labels:
     app: log-app
spec:
  containers:
  - name: log-app
    image: rajeshg87/spring-logging-app:1.0
    ports:
      - containerPort: 8765
    env:
    - name: JVM_OPTS
      value: "-Xms64M -Xmx256M"
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "256Mi"